import Head from 'next/head'
// import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import WhatWeDo from '../components/whatWeDo/WhatWeDo'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container-fluid p-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="container-fluid"> */}
        <HeroSection/>
        <WhatWeDo />
      {/* </div> */}
    </div>
  )
}
