import Head from 'next/head'
import BlogIndex from '../components/blogIndex/BlogIndex'
import HeroBanner1 from '../components/heroBanner1/HeroBanner1'
// import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import ShopIndex from '../components/shopIndex/ShopIndex'
import Testimonial from '../components/testimonial/Testimonial'
import WhatWeDo from '../components/whatWeDo/WhatWeDo'
import WhatWeDoBest from '../components/whatWeDoBest/WhatWeDoBest'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container-fluid p-0">
      <Head>
      {/* <meta name="viewport" content="width=device-width,initial-scale=1"/> */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
      </Head>
      {/* <div className="container-fluid"> */}
        <HeroSection/>
        <WhatWeDo />
        <HeroBanner1 />
        <WhatWeDoBest />
        <Testimonial />
        <BlogIndex />
        <ShopIndex />
      {/* </div> */}
    </div>
  )
}
